### ISSUE TITLE
ConcurrentModificationException in getLogs()

### ISSUE THREAD

**Issue by AndreyNudko** [Hakky54/log-captor#21]
We tried LogCaptor in some integration-style tests, where logging actually happens in background thread.
Occasionally getLogs() throws `ConcurrentModificationException` - 
 quick look into code shows that `ListAppender.list` is not thread-safe, so it's almost certainly a race between test and application threads. I think it's not a problem for actual logging since `AppenderBase::doAppend` is synchronized, but it is a problem when scanning the list.
One possible fix would be to wrap all access to list into `synchronized(listAppender)`. Or, maybe even better, swap it for CopyOnWrite / Collections::synchronizedList.
Any views on that? Happy to submit PR as well.

**Comment by Hakky54** [comment]
Hi Andrey

Thank you for mentioning this issue. It looks like it is indeed not thread safe. I think both suggestions sounds as a good solution and I am ok with you creating and submitting a pull request. Looking forward to it!

**Comment by Hakky54** [comment]
I just tried it out it it looks like synchronize will do the trick, just like you suggested by wrapping it with `synchronized(listAppender)` before accessing it. So I don't think `synchronizedList` is needed with this approach. What do you think?

**Comment by AndreyNudko** [comment]
Thanks for taking a look!
I was thinking using `synchronizedList` would be a slightly cleaner approach - it's contract clearly states that `It is imperative that the user manually synchronize on the returned list when traversing it via Iterator, Spliterator or Stream`. Synchronising on appender relies on implementation details of the base class, which are sort of explained in http://logback.qos.ch/manual/appenders.html#AppenderBase, but in less strict terms.
That said, I don't think it's a big deal - either approach will work.
I'll try to find some time to do PR in the next couple of days, unless you're going to make changes.

**Comment by Hakky54** [comment]
Sounds good, I am looking forward to your PR with the `synchronizedList`

**Comment by Hakky54** [comment]
@AndreyNudko I will publish this version in the coming days, I will keep you updated

**Comment by AndreyNudko** [comment]
@Hakky54 Awesome, thanks for the quick turnaround!

**Comment by Hakky54** [comment]
The latest changes are now available within version 2.7.1 @AndreyNudko
