### ISSUE TITLE
log4j

### ISSUE THREAD

**Issue by clementSabattie** [Hakky54/log-captor#25]
Because of this [Security Fail](https://logging.apache.org/log4j/2.x/security.html), I think it could use the newer version of log4j 

https://github.com/Hakky54/log-captor/blob/941da53163737c0dea130900f60b5ed8a6d9a757/pom.xml#L60

**Comment by Hakky54** [comment]
This property is not being used anymore, but somehow I forgot to remove it. 
I updated the other dependencies, see here: https://github.com/Hakky54/log-captor/commit/ced61fac89fd9594587bf44e722daddabd31e53b

And just released a new version `2.7.4` This should resolve the Log4j issue.
