### ISSUE TITLE
Add support for name based creation

### ISSUE THREAD

**Issue by tjuchniewicz** [Hakky54/log-captor#3]
Sometimes we have to monitor name based loggers and would be great to have such new method available:
```java
 public static LogCaptor<String> forName(String name) {
        return new LogCaptor<>(name);
 }
```

**Comment by Hakky54** [comment]
Hi @tjuchniewicz Thank you for stopping by and asking for this feature. It should be an easy implementation, I have already changed it, please have a look here: https://github.com/Hakky54/log-captor/commit/403c2f6e7852d9d2c65edb4327cfc701cb6aacb5

See here for an example usage/unit test: https://github.com/Hakky54/log-captor/blob/403c2f6e7852d9d2c65edb4327cfc701cb6aacb5/src/test/java/nl/altindag/log/LogCaptorShould.java#L56

Please let me know if you think this will work for you so I can make a release tomorrow

**Comment by tjuchniewicz** [comment]
Hi @Hakky54. Looks good for me. Thank you. I'm waiting for the next release!

**Comment by Hakky54** [comment]
Great, I just released it. Have fun!
I am not quite sure if your nexus will be able to resolve it today. If not it should definitely work tomorrow

**Comment by tjuchniewicz** [comment]
Works fine. Thank you once again @Hakky54 !

**Comment by Hakky54** [comment]
You're welcome!
