### ISSUE TITLE
Suppressing Console Output

### ISSUE THREAD

**Issue by bbeswick** [Hakky54/log-captor#42]
In my unit tests I have code that intentionally throws an exception to verify that it gets handled gracefully (message gets logged but execution continues in this case.)  I am successfully using LogCaptor to verify that the logging happened but the console ALSO shows the messages (and their associated stack traces) when the unit tests run - this makes for really long output.  While it is only an annoyance for me, it would be ideal to be able to suppress the console output of these messages since I am intentionally causing them and am using LogCaptor to verify that they happened.

In the closed issues section I see a brief discussion of such a feature in 2021 but it doesn't appear to have been merged back into the main code branch.  Does that feature sound like it fits this use case and, if so, can it be merged into the main code branch?

**Comment by Hakky54** [comment]
Hi @bbeswick 

The earlier issue you found was based on a different solution and I didn't liked that one actually. I was able to provide an alternative solution for the OP, however I think it is better to provide this kind of option out of the box from the library without any additional configuration files or environment properties. I understand your desire to turn of the output as it can get very verbose while still wanting to capture those logs. I create a PR, please have a look at it: https://github.com/Hakky54/log-captor/pull/43

I think this change will do the trick for you. If you want you can for this repo, build it locally and try it out to validate the changes on your side, but I think this will work. Please let me know whether this is ok for you and if you need anything else.

**Comment by Hakky54** [comment]
@bbeswick any remarks? If not I am going to merge the pr and mark this issue as resolved
