### ISSUE TITLE
Are we supposed to close LogCaptor at the end of a test?

### ISSUE THREAD

**Issue by rcrlik** [Hakky54/log-captor#45]
**Describe the bug**
This is more of a question. But colleague of mine noticed that `LogCaptor` implements `AutoCloseable` interface. So he asked if we should use try-with-resources or call close() method in the end of the test.

Because the simple example in the REAMDE file doesn't do that. It simply calls LogCaptor.forClass(...) stores it in the variable and that's it.

```
@Test
 public void logInfoAndWarnMessages() {
        LogCaptor logCaptor = LogCaptor.forClass(FooService.class);

        // just do some stuff
}
```

Is there any risk of not calling close() or not using the variation of reusing the captor between tests and using BeforeAll/AfterAll hooks?

**Environmental Data:**
 - LogCaptor version: 2.7.10
 - Java Version: 17
 - Gradle Version: 7.6
- OS: Windows/Linux

**Comment by Hakky54** [comment]
It is an overall good practice to either wrap logcaptor in a try with resource which in return calls the close method or you could call the close method explicitly.

In my examples I have not mentioned it indeed, I have not updated the documentation for quite some time. But not calling the close method or not wrapping it in a try with resource wont't harm in my opinion. If you look closely to the close method implementation you will understand that it is cleaner to call it: https://github.com/Hakky54/log-captor/blob/594afa6e3d9ef3822d8e8ee2c26aae6f3a13ef66/src/main/java/nl/altindag/log/LogCaptor.java#L223

I am not sure how it will behave in a an environment where a-lot instances are created for logcaptor are created, as I don't know yet the side effect of not calling the close method in that kind of environment. If that is not the case for your team then you omit it. I hope it makes a bit sense

**Comment by rcrlik** [comment]
It makes more sense now. Thank you for the clarification and for the library. It can really save some time :slightly_smiling_face:

**Comment by Hakky54** [comment]
Glad to hear that the library is useful for you!

By the way, feel free to submit a pull request for example regarding the try-woth-resource with an explanation if you want to contribute to the readme file or anything else if you have a cool idea 😁
