### ISSUE TITLE
Issue with custom levels

### ISSUE THREAD

**Issue by moaxcp** [Hakky54/log-captor#46]
**Describe the bug**

I'm not sure if I am doing something wrong but just adding the dependencies is causing tests to fail. Let me explain.

I am getting an error in classes that log to a custom level.

```
java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Level.getStandardLevel()" because "level" is null

	at org.apache.logging.slf4j.SLF4JLogger.isEnabledFor(SLF4JLogger.java:209)
```

**To Reproduce**

My company uses log4j2 with custom levels in the log4j settings.

```
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.19.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.19.0</version>
        </dependency>
```

The custom levels are added in the configuration.

```
<Configuration status="debug" name="product" packages="com.product.backend" monitorInterval="900">
    <CustomLevels>
        <CustomLevel name="PRODUCT_FINE" intLevel="460" />
        <CustomLevel name="PRODUCT_DEBUG" intLevel="450" />
    </CustomLevels>
    ...
```

Once I add log-captor to the dependencies I get the error. No tests have been written yet using log-captor.

When I debug I can check the LEVELS property and see that it does not contain the custom levels. Also the `forName` method is never called to add the levels from the custom configs.

**Expected behavior**

Support for custom levels. Maybe there is a trick that I didn't see in the readme. Any help is appreciated.

**Screenshots**

**Environmental Data:**
 - Java Version
 - Maven Version
- OS (Windows/Linux/MacOS)

**Additional context**

**Comment by Hakky54** [comment]
Can you maybe share the full stacktrace?

Any idea whether logcaptor is able is able to initialize at all or are you able to see that it captures any logs regardless if the level?

By the way did you configured your test scoped dependencies similar as documented here: https://github.com/Hakky54/log-captor#using-log-captor-alongside-with-other-logging-libraries

Looking forward to your response.
