### ISSUE TITLE
ava.lang.NoClassDefFoundError: org/slf4j/spi/LoggingEventAware

### ISSUE THREAD

**Issue by chintu24** [Hakky54/log-captor#52]
**Describe the bug**
Using the LogCaptor 2.9.2 in a Java project which is based on OSGi/ODL frameworks. It was working perfectly fine but recent changes to address security issues in the parent projects causes the JUnit tests to fail. The failure is the usual 
java.lang.ExceptionInInitializerError
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j

So, I added the exclusion as below
<dependency>
      <groupId>io.github.hakky54</groupId>
      <artifactId>logcaptor</artifactId>
      <version>2.9.2</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-to-slf4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

Now, the log4j-slf4j-impl cannot be present with log4j-to-slf4j issue is gone, but getting a different exception as below
java.lang.NoClassDefFoundError: org/slf4j/spi/LoggingEventAware
	at com.fujitsu.fnc.mdsaladaptor.util.MDSalUtilTest.<clinit>(MDSalUtilTest.java:49)
The line number (49 as an example in the above exception) is the line where the LogCaptor is initialized as below
private static final LogCaptor logCaptor = LogCaptor.forClass(MDSALUtil.class);

**To Reproduce**
As described above

**Expected behavior**
How to get past the NoClassDefFoundError:  org/slf4j/spi/LoggingEventAware

**Screenshots**

**Environmental Data:**
 - Java Version - openjdk version 11.0.21
 - Maven Version - Apache Maven 3.6.3
- OS Linux

**Additional context**
mvn dependency tree output (without the exclusion)
 com.fujitsu.fnc.mdsaladaptor:mdsaladaptor-impl:bundle:7.3.0-SNAPSHOT
 +- com.fujitsu.fnc.model:sdn-model:jar:7.3.0-SNAPSHOT:compile
 |  +- org.opendaylight.mdsal:yang-binding:jar:2.0.17:compile
 |  +- org.opendaylight.yangtools:yang-common:jar:3.0.16:compile
 |  +- org.opendaylight.mdsal.binding.model.ietf:rfc6991-ietf-yang-types:jar:2.0.17:compile
 |  |  \- org.opendaylight.mdsal.model:ietf-type-util:jar:3.0.17:compile
 |  +- org.opendaylight.mdsal.binding.model.ietf:rfc6991-ietf-inet-types:jar:2.0.17:compile
 |  +- org.opendaylight.mdsal.model:ietf-topology-l3-unicast-igp:jar:2013.10.21.16.17:compile
 |  |  \- org.opendaylight.mdsal.model:ietf-topology:jar:2013.10.21.16.17:compile
 |  +- org.opendaylight.mdsal.model:yang-ext:jar:2013.09.07.16.17:compile
 |  +- com.google.guava:guava:jar:32.1.1-jre:compile
 |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
 |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
 |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
 |  |  +- org.checkerframework:checker-qual:jar:3.33.0:compile
 |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
 |  +- org.opendaylight.yangtools:concepts:jar:3.0.16:compile
 |  \- com.fujitsu.fnc.thirdparty:openroadm-model:jar:7.3.0-SNAPSHOT:compile
 |     +- org.opendaylight.mdsal.binding.model.ietf:rfc8345-ietf-network:jar:2.0.17:compile
 |     +- org.opendaylight.mdsal.binding.model.ietf:rfc8345-ietf-network-topology:jar:2.0.17:compile
 |     +- org.opendaylight.mdsal.model:iana-afn-safi:jar:2013.07.04.16.17:compile
 |     +- org.opendaylight.netconf:ietf-netconf:jar:1.7.4:compile
 |     +- edu.umd.cs.findbugs:annotations:jar:1.0.0:compile
 |     \- com.wordnik:swagger-annotations:jar:1.3.9:compile
 +- com.fujitsu.fnc.sdnfw:kafka-provider-api:jar:7.3.0-SNAPSHOT:compile
 |  +- com.google.code.gson:gson:jar:2.10.1:compile
 |  \- javax.xml.bind:jaxb-api:jar:2.3.1:compile
 |     \- javax.activation:javax.activation-api:jar:1.2.0:compile
 +- org.opendaylight.mdsal:mdsal-binding-api:jar:4.0.17:compile
 |  +- org.opendaylight.mdsal:mdsal-common-api:jar:4.0.17:compile
 |  \- org.opendaylight.mdsal.model:general-entity:jar:2.0.17:compile
 +- org.opendaylight.mdsal:mdsal-dom-api:jar:4.0.17:compile
 +- org.opendaylight.mdsal:mdsal-common-util:jar:4.0.17:compile
 +- org.opendaylight.controller:sal-clustering-commons:jar:1.10.4:compile
 +- org.opendaylight.mdsal:mdsal-binding-spec-util:jar:2.0.17:compile
 +- org.osgi:org.osgi.core:jar:6.0.0:compile
 +- org.opendaylight.mdsal:mdsal-binding-dom-codec:jar:4.0.17:compile
 |  +- org.javassist:javassist:jar:3.26.0-GA:compile
 |  \- org.opendaylight.yangtools:yang-data-impl:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc7952-data-util:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc8528-data-util:jar:3.0.16:compile
 |     \- org.antlr:antlr4-runtime:jar:4.7.2:compile
 +- org.opendaylight.mdsal:mdsal-binding-generator-api:jar:2.0.17:compile
 +- org.opendaylight.mdsal:mdsal-binding-generator-impl:jar:2.0.17:compile
 |  \- org.opendaylight.yangtools:yang-parser-impl:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:yang-parser-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:yang-parser-reactor:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:yang-parser-spi:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:yang-parser-rfc7950:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:odlext-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:odlext-parser-support:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:openconfig-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:openconfig-parser-support:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc6241-model-api:jar:1.0.16:compile
 |     +- org.opendaylight.yangtools:rfc6241-parser-support:jar:1.0.16:compile
 |     +- org.opendaylight.yangtools:rfc6536-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc6536-parser-support:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc7952-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc7952-parser-support:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc8040-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc8040-parser-support:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc8528-model-api:jar:3.0.16:compile
 |     +- org.opendaylight.yangtools:rfc8528-parser-support:jar:3.0.16:compile
 |     \- org.opendaylight.yangtools:yang-xpath-impl:jar:1.0.16:compile
 +- org.opendaylight.mdsal:mdsal-binding-generator-util:jar:2.0.17:compile
 |  \- org.opendaylight.yangtools:yang-model-util:jar:3.0.16:compile
 +- org.opendaylight.yangtools:yang-data-api:jar:3.0.16:compile
 |  \- org.opendaylight.yangtools:util:jar:3.0.16:compile
 |     \- tech.pantheon.triemap:triemap:jar:1.1.0:compile
 +- org.osgi:org.osgi.compendium:jar:5.0.0:compile
 +- com.fujitsu.fnc.mdsaladaptor:mdsaladaptor-api:jar:7.3.0-SNAPSHOT:compile
 |  \- org.json:json:jar:20231013:compile
 +- de.danielbechler:java-object-diff:jar:0.92:compile
 +- commons-io:commons-io:jar:2.13.0:compile
 +- org.opendaylight.yangtools:yang-data-codec-gson:jar:3.0.16:compile
 |  \- org.opendaylight.yangtools:yang-data-util:jar:3.0.16:compile
 |     \- org.opendaylight.yangtools:rfc8528-data-api:jar:3.0.16:compile
 +- org.opendaylight.yangtools:yang-data-codec-xml:jar:3.0.16:compile
 |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
 |  \- org.opendaylight.yangtools:rfc7952-data-api:jar:3.0.16:compile
 +- org.opendaylight.netconf:netconf-api:jar:1.7.4:compile
 |  +- io.netty:netty-transport:jar:4.1.51.Final:compile
 |  |  +- io.netty:netty-common:jar:4.1.51.Final:compile
 |  |  +- io.netty:netty-buffer:jar:4.1.51.Final:compile
 |  |  \- io.netty:netty-resolver:jar:4.1.51.Final:compile
 |  +- org.opendaylight.netconf:ietf-netconf-monitoring:jar:1.7.4:compile
 |  +- org.opendaylight.netconf:ietf-netconf-monitoring-extension:jar:1.7.4:compile
 |  \- org.opendaylight.mdsal.binding.model.ietf:rfc6991:jar:2.0.17:compile
 +- org.opendaylight.yangtools:yang-model-api:jar:3.0.16:compile
 |  \- org.opendaylight.yangtools:yang-xpath-api:jar:1.0.16:compile
 +- org.apache.karaf.shell:org.apache.karaf.shell.console:jar:4.3.9:compile
 |  +- org.jline:jline:jar:3.21.0:compile
 |  +- org.fusesource.jansi:jansi:jar:2.4.0:compile
 |  +- org.apache.karaf.jaas:org.apache.karaf.jaas.modules:jar:4.3.9:compile
 |  |  +- org.apache.karaf.jaas:org.apache.karaf.jaas.config:jar:4.3.9:compile
 |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
 |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
 |  |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3:compile
 |  |  |  +- org.glassfish.jaxb:txw2:jar:2.3.3:compile
 |  |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.11:compile
 |  |  |  \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
 |  |  \- javax.activation:activation:jar:1.1.1:compile
 |  +- org.apache.karaf.jaas:org.apache.karaf.jaas.boot:jar:4.3.9:compile
 |  +- org.apache.karaf.shell:org.apache.karaf.shell.core:jar:4.3.9:compile
 |  \- org.apache.sshd:sshd-osgi:jar:2.9.2:compile
 +- io.github.hakky54:logcaptor:jar:2.9.2:test
 |  +- ch.qos.logback:logback-classic:jar:1.3.14:test
 |  |  \- ch.qos.logback:logback-core:jar:1.3.14:test
 |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.22.0:test
 |  \- org.slf4j:jul-to-slf4j:jar:2.0.9:test
 +- org.slf4j:slf4j-api:jar:1.7.25:compile
 +- org.javatuples:javatuples:jar:1.2:compile
 +- com.fasterxml.jackson.core:jackson-databind:jar:2.16.1:provided
 |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.16.1:provided
 |  \- com.fasterxml.jackson.core:jackson-core:jar:2.16.1:provided
 +- org.apache.kafka:kafka-clients:jar:3.2.0:compile
 |  +- com.github.luben:zstd-jni:jar:1.5.2-1:runtime
 |  +- org.lz4:lz4-java:jar:1.8.0:runtime
 |  \- org.xerial.snappy:snappy-java:jar:1.1.8.4:runtime
 +- org.mockito:mockito-inline:jar:3.9.0:test
 +- org.robolectric:robolectric-utils:jar:3.1.2:test
 |  +- org.ow2.asm:asm:jar:5.0.1:test
 |  +- org.ow2.asm:asm-commons:jar:5.0.1:test
 |  |  \- org.ow2.asm:asm-tree:jar:5.0.1:test
 |  +- org.robolectric:robolectric-annotations:jar:3.1.2:test
 |  \- com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:jar:2.1:test
 |     +- org.hamcrest:hamcrest-library:jar:1.3:test
 |     \- com.google.protobuf:protobuf-java:jar:2.6.1:test
 +- com.theoryinpractise:googleformatter-maven-plugin:maven-plugin:1.0.6:compile
 |  +- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.4:compile
 |  |  \- org.apache.maven:maven-artifact:jar:3.0:compile
 |  +- org.codehaus.plexus:plexus-utils:jar:2.0.5:compile
 |  +- org.apache.maven:maven-plugin-api:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-model:jar:3.3.9:compile
 |  |  \- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.2:compile
 |  |     +- javax.enterprise:cdi-api:jar:1.0:compile
 |  |     |  \- javax.annotation:jsr250-api:jar:1.0:compile
 |  |     \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.2:compile
 |  +- org.apache.maven:maven-core:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-settings:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-settings-builder:jar:3.3.9:compile
 |  |  |  \- org.apache.maven:maven-builder-support:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-repository-metadata:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-model-builder:jar:3.3.9:compile
 |  |  +- org.apache.maven:maven-aether-provider:jar:3.3.9:compile
 |  |  |  \- org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
 |  |  +- org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
 |  |  +- org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
 |  |  +- org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
 |  |  +- com.google.inject:guice:jar:no_aop:4.0:compile
 |  |  |  +- javax.inject:javax.inject:jar:1:compile
 |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
 |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
 |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
 |  |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
 |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
 |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
 |  +- org.codehaus.plexus:plexus-compiler-api:jar:2.3:compile
 |  +- org.apache.maven.scm:maven-scm-api:jar:1.9.4:compile
 |  +- org.apache.maven.scm:maven-scm-manager-plexus:jar:1.9.4:compile
 |  |  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
 |  |     \- classworlds:classworlds:jar:1.1-alpha-2:compile
 |  +- org.apache.maven.scm:maven-scm-providers-standard:pom:1.9.4:compile
 |  |  +- org.apache.maven.scm:maven-scm-provider-accurev:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-bazaar:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-clearcase:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-cvsexe:jar:1.9.4:runtime
 |  |  |  \- org.apache.maven.scm:maven-scm-provider-cvs-commons:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-cvsjava:jar:1.9.4:runtime
 |  |  |  +- org.netbeans.lib:cvsclient:jar:20060125:runtime
 |  |  |  \- ch.ethz.ganymed:ganymed-ssh2:jar:build210:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-gitexe:jar:1.9.4:runtime
 |  |  |  +- commons-lang:commons-lang:jar:2.6:runtime
 |  |  |  \- org.apache.maven.scm:maven-scm-provider-git-commons:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-hg:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-perforce:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-starteam:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-svnexe:jar:1.9.4:runtime
 |  |  |  \- org.apache.maven.scm:maven-scm-provider-svn-commons:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-synergy:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-vss:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-tfs:jar:1.9.4:runtime
 |  |  +- org.apache.maven.scm:maven-scm-provider-integrity:jar:1.9.4:runtime
 |  |  |  +- com.mks.api:mksapi-jar:jar:4.10.9049:runtime
 |  |  |  \- org.codehaus.groovy:groovy-all:jar:1.7.6:runtime
 |  |  \- org.apache.maven.scm:maven-scm-provider-jazz:jar:1.9.4:runtime
 |  +- com.google.truth:truth:jar:0.28:compile
 |  +- com.google.googlejavaformat:google-java-format:jar:1.0:compile
 |  |  +- com.beust:jcommander:jar:1.47:compile
 |  |  \- org.eclipse.jdt:org.eclipse.jdt.core:jar:3.10.0:compile
 |  |     +- org.eclipse.core:org.eclipse.core.resources:jar:3.7.100:compile
 |  |     |  \- org.eclipse.core:org.eclipse.core.expressions:jar:3.4.300:compile
 |  |     +- org.eclipse.core:org.eclipse.core.runtime:jar:3.7.0:compile
 |  |     |  +- org.eclipse.osgi:org.eclipse.osgi:jar:3.7.1:compile
 |  |     |  +- org.eclipse.equinox:org.eclipse.equinox.common:jar:3.6.0:compile
 |  |     |  +- org.eclipse.core:org.eclipse.core.jobs:jar:3.5.100:compile
 |  |     |  +- org.eclipse.equinox:org.eclipse.equinox.registry:jar:3.5.101:compile
 |  |     |  +- org.eclipse.equinox:org.eclipse.equinox.preferences:jar:3.4.1:compile
 |  |     |  +- org.eclipse.core:org.eclipse.core.contenttype:jar:3.4.100:compile
 |  |     |  \- org.eclipse.equinox:org.eclipse.equinox.app:jar:1.3.100:compile
 |  |     +- org.eclipse.core:org.eclipse.core.filesystem:jar:1.3.100:compile
 |  |     \- org.eclipse.text:org.eclipse.text:jar:3.5.101:compile
 |  |        \- org.eclipse.core:org.eclipse.core.commands:jar:3.6.0:compile
 |  \- com.google.errorprone:error_prone_annotations:jar:2.0.9:compile
 +- au.com.acegi:xml-format-maven-plugin:maven-plugin:3.2.0:compile
 |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
 |  \- org.dom4j:dom4j:jar:2.0.3:compile
 +- org.mockito:mockito-core:jar:3.5.10:compile
 |  +- net.bytebuddy:byte-buddy:jar:1.10.13:compile
 |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.13:compile
 |  \- org.objenesis:objenesis:jar:3.1:compile
 +- junit:junit:jar:4.13:compile
 |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
 +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
 |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
 |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
 |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
 |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
 |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
 +- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
 +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.20.0:compile
 |  \- org.apache.logging.log4j:log4j-core:jar:2.20.0:runtime
 +- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
 +- org.apache.logging.log4j:log4j-api:jar:2.20.0:compile
 +- commons-net:commons-net:jar:3.9.0:compile
 +- org.powermock:powermock-api-mockito2:jar:2.0.7:test
 |  \- org.powermock:powermock-api-support:jar:2.0.7:test
 |     +- org.powermock:powermock-reflect:jar:2.0.7:test
 |     \- org.powermock:powermock-core:jar:2.0.7:test
 +- org.powermock:powermock-module-junit4:jar:2.0.7:test
 |  \- org.powermock:powermock-module-junit4-common:jar:2.0.7:test
 +- org.apache.felix:org.apache.felix.scr.annotations:jar:1.9.6:compile
 +- org.apache.felix:org.apache.felix.scr:jar:1.8.2:compile
 |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.9:compile
 +- org.apache.felix:org.apache.felix.framework:jar:4.2.1:compile
 \- org.eclipse.jdt:org.eclipse.jdt.annotation:jar:2.2.100:compile

**Comment by Hakky54** [comment]
Thank you for the detailed information, this is very useful.

It looks like you are mainy using log4j which is ok and it should work, however I noticed you are having slf4j libraries of version 1.x.x which are nog compatible with logcaptor v2.8.0 onwards. My suggestion is to migrate all of your slf4j libraries to the latest if possible. I think that would be overall better solution, however if that would take too much time or if it is not possible you can use logcaptor version 2.7.10 which is still compatible with your project.

Can you please give it a try and share your results here?

**Comment by chintu24** [comment]
Hi @Hakky54 thanks for your inputs and sorry about the delayed reply. I went with your first suggestion of using the more recent version of slf4fj libraries (but only for the unit tests). I cannot downgrade the logcaptor to 2.7.10 as it misses an important functionality. The 2.9.x version has the disableConsoleOutput()/enableConsoleOutput() which is not present in the 2.7.10. We use other third party libraries which for some reason starts logging the information at DEBUG level when I set the logging level to DEBUG for our code (during the unit tests). Without this disableConsoleOutput() the UTs takes more than 30 minutes to finish (if I disable the console output, then the UTs finish in 30 to 45 seconds).

**Comment by Hakky54** [comment]
I see, I understand the issue you are facing. You are stuck with the older version of SLF4J and can't upgrade and you want to use the latest version of LogCaptur because of the disableConsoleOutput method. I didn't know disabling the console output would have that much of an impact on while running the tests!

I have made a new release which has the `disableConsoleOutput()/enableConsoleOutput()` methods. It is backported from the `2.9.x`. It is available in version `2.7.11` which is compatible with older versions of SLF4J. Can you give it a try and share your results here?

**Comment by yeikel** [comment]
I am also facing this challenge with older versions of `slf4j` . Unbfonratly, I am in an environment where I cannot upgrade `slf4j` freely 

```xml

<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-ext</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.hakky54</groupId>
            <artifactId>logcaptor</artifactId>
            <version>2.9.2</version>
            <scope>test</scope>
        </dependency>

```

```java
var logCaptor = LogCaptor.forClass(CustomBasicAuthFilter.class);
logCaptor.setLogLevelToTrace();
logCaptor.disableConsoleOutput();

```

```java

java.lang.NoClassDefFoundError: org/slf4j/spi/LoggingEventAware

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at nl.altindag.log.LogCaptor.<init>(LogCaptor.java:59)
	at nl.altindag.log.LogCaptor.forClass(LogCaptor.java:86)

```

**Comment by yeikel** [comment]
Removing `slf4j-simple` from my classpath and using version `2.7.10` seems to help for now

**Comment by Hakky54** [comment]
> Removing `slf4j-simple` from my classpath and using version `2.7.10` seems to help for now

Can you use version 2.7.11 
I released that one previous week and should work for your use case. The method disableconsoleoutput has been added to that version

**Comment by yeikel** [comment]
> > Removing `slf4j-simple` from my classpath and using version `2.7.10` seems to help for now
> 
> Can you use version 2.7.11 I released that one previous week and should work for your use case. The method disableconsoleoutput has been added to that version

Thank you for the response. It turns out that I need to keep `slf4j-simple` in the classpath and that does not seem to play well with the library. A configuration like : 

```xml
 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-ext</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.hakky54</groupId>
            <artifactId>logcaptor</artifactId>
            <version>2.7.11</version>
            <scope>test</scope>
        </dependency>
```

Leads to : 

```java
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/yeikel/.m2/repository/org/slf4j/slf4j-simple/1.7.36/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/yeikel/.m2/repository/ch/qos/logback/logback-classic/1.2.13/logback-classic-1.2.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

java.lang.IllegalArgumentException: SLF4J Logger implementation should be of the type [ch.qos.logback.classic.Logger] but found [org.slf4j.impl.SimpleLogger].

	at nl.altindag.log.util.ValidationUtils.requireLoggerOfType(ValidationUtils.java:36)
	at nl.altindag.log.LogCaptor.<init>(LogCaptor.java:59)
	at nl.altindag.log.LogCaptor.forClass(LogCaptor.java:86)

```

Which is confusing because I do not have logback in my classpath at all/I do not use logback

**Comment by yeikel** [comment]
I think that the main issue is that the library does not support `slf4j-simple`

**Comment by Hakky54** [comment]
The short answer to your issue is that you need to exclude slf4j-simple during the test phase, see also this documentation section on the main page of this library: https://github.com/Hakky54/log-captor?tab=readme-ov-file#using-log-captor-alongside-with-other-logging-libraries

Let me try to give a bit of context. This library uses slf4j API and it forwards logs from other logging APIs such as log4j2 api. Slf4j- api is not bundled with an implementation, it just contains an logging api. Slf4j-simple, logback and other libraries are logging implementation of the api. logcaptor uses logback as api implementation to capture the logs. There is a strict rule when using slf4j-api, where it will allow to have only one api implementation on the class path. So in order to allow logcaptor to work properly you need to exclude all other slf4j implementations, if you happen to have multiple implementations, during your test phase. This is also explained with examples in the link which I shared. Please give it a try, I am pretty sure it will work for you or else feel free to drop a message here

**Comment by yeikel** [comment]
> The short answer to your issue is that you need to exclude slf4j-simple during the test phase, see also this documentation section on the main page of this library: https://github.com/Hakky54/log-captor?tab=readme-ov-file#using-log-captor-alongside-with-other-logging-libraries
> 
> Let me try to give a bit of context. This library uses slf4j API and it forwards logs from other logging APIs such as log4j2 api. Slf4j- api is not bundled with an implementation, it just contains an logging api. Slf4j-simple, logback and other libraries are logging implementation of the api. logcaptor uses logback as api implementation to capture the logs. There is a strict rule when using slf4j-api, where it will allow to have only one api implementation on the class path. So in order to allow logcaptor to work properly you need to exclude all other slf4j implementations, if you happen to have multiple implementations, during your test phase. This is also explained with examples in the link which I shared. Please give it a try, I am pretty sure it will work for you or else feel free to drop a message here

Thank you for the context. I imagine that this error is also related : 

> org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j


```xml

 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-ext</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
        </dependency>

```

**Comment by Hakky54** [comment]
@yeikel did the solution work for you? Just checking whether we can resolve this issue

**Comment by yeikel** [comment]
> @yeikel did the solution work for you? Just checking whether we can resolve this issue. So are you now able to use logcaptor without any other issue?

I have the following list of dependencies : 

```xml
<properties>
 <slf4j.version>1.7.36</slf4j.version>
<log4j.version>2.22.1</log4j.version>
</properties>

 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-ext</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
        </dependency>

```

Using `logcaptor` `2.7.11` along with the custom surfire configuration fixed the issue for me 


```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <classpathDependencyExcludes>
                        <classpathDependencyExclude>org.apache.logging.log4j:log4j-slf4j-impl</classpathDependencyExclude>
                    </classpathDependencyExcludes>
                </configuration>
            </plugin>

```

I also tried `2.9.2` does not seem to be compatible with  `slf4j` 1.x as that throws `java.lang.NoClassDefFoundError: org/slf4j/spi/LoggingEventAware`
