### ISSUE TITLE
IllegalArgumentException while using logcaptor 

### ISSUE THREAD

**Issue by DurgaManasaMaruboyina** [Hakky54/log-captor#84]
**Describe the bug**
Logcaptor is not working as expected. Getting the IllegalArgumentException

**To Reproduce**
1. Use log captor as mentioned in the readme 
2. Getting this error when using it `java.lang.IllegalArgumentException: SLF4J Logger implementation should be of the type [ch.qos.logback.classic.Logger] but found [org.slf4j.impl.Slf4jLogger].`

We are using quarkus and logger from org.jboss.logging.Logger which implements Slf4jLogger. 

Is it forcing us to use logback logger only instead Slf4jlogger? 

We excluded the mentioned configuration and after that it's giving the class loader error 

`<classpathDependencyExcludes>
                              <classpathDependencyExclude>org.jboss.slf4j:slf4j-jboss-logmanager</classpathDependencyExclude>
  </classpathDependencyExcludes>`

**Comment by Hakky54** [comment]
It is enforcing to use Logback indeed. SLF4J api allows to only use one implementation and therefor to have LogCaptor working all other implementations needs to be excluded during the test phase.

> We excluded the mentioned configuration and after that it's giving the class loader error

Can you share the classloader issue/error?
