### ISSUE TITLE
Prevent all loggers from printing to stdout

### ISSUE THREAD

**Issue by angelsanzn** [Hakky54/log-captor#9]
**Is your feature request related to a problem? Please describe.**
When LogCaptor is launched, it makes all loggers log to the most verbose level, and they print to stdout. This is making my tests slow by an order of magnitude (from less than 1s to around 5s), because some libraries I invoke in the tests log very heavily.

More so, in some tests where the input data is very large and it happens to gets logged by an underlying library, the tests time out because the printing to stdout takes very long. I could work around this using .disableLogs, but that couples my test to a bunch of internal class names of the underlying library.

**Describe the solution you'd like**
I would like to have a way to configure LogCaptor to prevent all loggers from printing to stdout. This would not change how logging levels are currently handled by LogCaptor (as opposed to what .disableLogs does). The logged messages and objects would still be kept in memory in order to later assert against them with the current API.

This could even be the default behavior, although that might be a breaking change for some people.

In case it is not the default behaviour, it could be configured with an environment variable. What do you think?

**Describe alternatives you've considered**
An alternative is to manually disable all printing to stdout altogether. However, this would wipe out all other strings printed to stdout which are not logs (e.g. messages from the test runner or other testing libraries).

Another alternative is to add one .disableLogs call per verbose logging class somewhere before the test starts running, but that's fragile as it couples the tests to the logging implementation of each verbose logging library.

**Comment by Hakky54** [comment]
Hi Ángel,

Thank you for creating this issue and asking for this kind of feature of disabled log output to the console without losing the capability of capturing it. I will work on an implementation to have this feature included with the next release. I will update you when it is ready.

**Comment by Hakky54** [comment]
Initial implementation is ready and it works. Please have a look. You can also fork the repo and test it locally and see if this solution is working for your use case. Looking forward to get your feedback

**Comment by angelsanzn** [comment]
Hi Hakan,

Many thanks for the very quick reply! Let me take a closer look, as the implementation looks nice but I just tested it and I encountered two problems:

- I can still see logs from all the loggers I didn't explicitly disable.
- I'm getting an OutOfMemoryError in the second or third test from my suite.

**Comment by angelsanzn** [comment]
Aside from that, I have a couple of comments about the solution:

1. I only really need to disable console output for all loggers. So I would only use this with `LogCaptor.forRoot().disableConsoleOutput();`. It's not necessary to be able to disable it selectively for some loggers.
1. Why not make this behavior the default? Do you think there will be a use case for showing logs on the console? What one wants is precisely to test logs, so printing them could even incentivize people to not test them.
1. If you still want to make this behavior optional, why not allow it to be configured globally with an environment variable? This would reduce the burden on the user of the library, because they would not need to sprinkle their code with calls to .disableConsoleOutput. Just setting an env var in the test run configuration would be enough. Moreover, I believe that the first problem I just mentioned has to do with the timing when the call to .disableConsoleOutput is made. Even placing it in a static initializer block of my test class was too late, as my test run still prints to console both logs which I believe are logged before the static initializer block and logs which are clearly logged after the static initializer block.

**Comment by Hakky54** [comment]
There are different ways to apply this feature, but I could not decide yet what would be the best way. I want to avoid using environment variables because you need additional documentation to  for the end-user to configure these option. It will be more dev friendly in my opinion if every possible configuration is programatically callable from the LogCaptor object. I will keep the option open as you have told you really prefer it like that. Another option is to disable the console output by default, even though that is possible I encountered an issue with a different feature regarding MDC. So this feature request will take some more time than expected.

While I am working on the possible implementation, would it be possible from your side to create a basic github project where I can reproduce the issue which you have regarding `OutOfMemoryError`?

**Comment by Hakky54** [comment]
Really great to get feedback on this, and strange that it is not working. I could not find an out of the box solution within the capability of SLF4J/Logback therefore I used a different approach. Can you retry it with the latest commit and having the following VM argument: `-DdisableConsoleOutput=true`

**Comment by Hakky54** [comment]
Hi @angelsanzn any updates from your side?

**Comment by angelsanzn** [comment]
Thanks for the logback config suggestion. That one definitely stops all printing of logs. However, my tests are still somehow choking, not with an OOM but apparently getting blocked by something and then timing out. I have to investigate a bit more and maybe put together a minimal repro. I'll also try the custom VM argument you introduced support for and will get back to you soon. Thanks!
