### ISSUE TITLE
java.lang.ClassNotFoundException: ch.qos.logback.core.Appender

### ISSUE THREAD

**Issue by rivancic** [Hakky54/log-captor#91]
**Describe the bug**
I'm using library with slf4j and log4j2 logger implementation.
I tying to test logging with LogCaptor. Following is the 
```java
  @Test
  void logWithPayload() throws Exception {
    LogCaptor logCaptor = LogCaptor.forClass(RequestResponseLoggingFilter.class);
    request.addHeader("X-B3-TraceId", "0815");
    ...
    filter.doFilterInternal(request, response, filterChain);
    verify(filterChain).doFilter(any(), any());
    assertThat(logCaptor.getInfoLogs()).containsExactly("Keyboard not responding. Press any key to continue...");
  }
```

While I get exception already at the `LogCaptor logCaptor = LogCaptor.forClass(RequestResponseLoggingFilter.class);` line.

**To Reproduce**
1 Included test dependencies
```groovy
  testImplementation "jakarta.servlet:jakarta.servlet-api"
  testImplementation "org.springframework.boot:spring-boot-starter-log4j2"
  testImplementation "org.springframework.boot:spring-boot-starter-test"
  testImplementation "org.springframework.security:spring-security-test"
  testImplementation("io.github.hakky54:logcaptor:2.9.2")
  testCompileOnly "junit:junit"
  testRuntimeOnly "org.junit.vintage:junit-vintage-engine"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"

```

2. Run the above mentioned test

3. Full stack trace
```
ch.qos.logback.core.Appender
java.lang.ClassNotFoundException: ch.qos.logback.core.Appender
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.crealogix.infrastructure.rest.logging.RequestResponseLoggingFilterTest.logWithPayload(RequestResponseLoggingFilterTest.java:56)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Expected behavior**
LogCaptor works out of the box with slf4j and log4j2 as described in tested log libraries section of Readme.

**Screenshots**
/

**Environmental Data:**
 - Java Version 17
 - Gradle 8.5
- OS (Windows)

**Additional context**
Will add if needed..

**Comment by Hakky54** [comment]
Hi Renato, 

It is for me not possible to reproduce it as your list of dependencies are mssing the versions. Would it be possible for you to add the dependency versions?

It has proven to work with slf4j and log4j2, so I think your issue is mostl likly related to transitive dependency, an old one overruling the one which is compatible with LogCaptor itself. But I think if you provide the dependency versions, I can quickly find out.

**Comment by rivancic** [comment]
After some debugging I found that the root project excludes `ch.qos.logback` dependencies because of the `slf4j` requirement to have only one implementation on the classpath.
```
configurations.configureEach {
  exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
  exclude group: 'org.apache.logging.log4j', module: 'log4j-to-slf4j'
  exclude group: 'ch.qos.logback', module: 'logback-classic'
}
```

I assumed that your library selects specific logging library based on what is available on the classpath. 
Now I see it depends on `ch.qos.logback:logback-core`.
